// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Node interface {
	IsNode()
}

type Competition struct {
	ID              string       `json:"id"`
	Year            string       `json:"year"`
	Country         string       `json:"country"`
	PrevCompetition *Competition `json:"prevCompetition"`
	NextCompetition *Competition `json:"nextCompetition"`
}

func (Competition) IsNode() {}

type Filter struct {
	Eq    string `json:"eq"`
	Regex string `json:"regex"`
}

type Match struct {
	ID      string `json:"id"`
	Year    int    `json:"year"`
	Stage   string `json:"stage"`
	Stadium string `json:"stadium"`
	City    string `json:"city"`
}

func (Match) IsNode() {}

type Player struct {
	Name      string   `json:"name"`
	MatchList []*Match `json:"matchList"`
}
