// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Competition struct {
	Year            string       `json:"year"`
	Country         string       `json:"country"`
	PrevCompetition *Competition `json:"prevCompetition"`
	NextCompetition *Competition `json:"nextCompetition"`
}

type Match struct {
	Stage string `json:"stage"`
}

type Player struct {
	Name string `json:"name"`
}
